// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3RcX-xBaiTfV9fZ99oEiYoMwectK2Q_w',
    appId: '1:576301829616:web:7e18343d97e0f04b286135',
    messagingSenderId: '576301829616',
    projectId: 'carrot-market-3c723',
    authDomain: 'carrot-market-3c723.firebaseapp.com',
    storageBucket: 'carrot-market-3c723.appspot.com',
    measurementId: 'G-9N7857FGXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB98WFsEsvR0ebNEm6-aGFGp411THu1spw',
    appId: '1:576301829616:android:aac8e46b473f6ae5286135',
    messagingSenderId: '576301829616',
    projectId: 'carrot-market-3c723',
    storageBucket: 'carrot-market-3c723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvoLbPMoiMDAySq4WUiryTKFQ2hyRPi48',
    appId: '1:576301829616:ios:2844700e1bb16b15286135',
    messagingSenderId: '576301829616',
    projectId: 'carrot-market-3c723',
    storageBucket: 'carrot-market-3c723.appspot.com',
    iosBundleId: 'com.example.fastAppBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvoLbPMoiMDAySq4WUiryTKFQ2hyRPi48',
    appId: '1:576301829616:ios:2844700e1bb16b15286135',
    messagingSenderId: '576301829616',
    projectId: 'carrot-market-3c723',
    storageBucket: 'carrot-market-3c723.appspot.com',
    iosBundleId: 'com.example.fastAppBase',
  );
}
